#ifndef GENSEQ_PINS_H
#define GENSEQ_PINS_H

// PIN ASSIGNMENTS & CONFIG

#define LED_PIN 25
#define LED_MATRIX_PIN 16

// UART MIDI
#define MIDI_UART uart1    // Using UART1 for MIDI
#define MIDI_UART_PIN_TX 8 // MIDI_UART_TX
#define MIDI_UART_PIN_RX 9 // MIDI_UART_RX

#endif // GENSEQ_PINS_H
